#!/bin/sh

# X11 application sandbox
# Originally based on http://blog.sleeplessbeastie.eu/2013/07/19/how-to-create-browser-sandbox/

# display used to show browser
XSUNABA_DISPLAY=":32"

# sandbox user
XSUNABA_USER="xsunaba"

# authentication cookie
XSUNABA_MCOOKIE=`openssl rand -hex 16`

# authentication file
XSUNABA_XAUTH="$HOME/.Xauthority-xsunaba"

# local X11 sockets, used to determine if application is running
LOCAL_SOCKETS="/tmp/.X11-unix"

# window width and height
WIDTH=1024
HEIGHT=768

# application to start
# width and height are raised above window dimensions to occupy full window
APPLICATION="$@" # -geometry $(expr $WIDTH + 1)x$(expr $HEIGHT + 1)"

if [ ! -e ${LOCAL_SOCKETS}/X${XSUNABA_DISPLAY#:} ]; then
  # display is not active

  # store authentication cookie for chosen display
  xauth -f ${XSUNABA_XAUTH} add ${XSUNABA_DISPLAY} . ${XSUNABA_MCOOKIE}
  doas -u $XSUNABA_USER xauth add ${XSUNABA_DISPLAY} . ${XSUNABA_MCOOKIE}

  # start Xephyr and application
  Xephyr -auth ${XSUNABA_XAUTH} -screen ${WIDTH}x${HEIGHT} -br -nolisten tcp $XSUNABA_DISPLAY &
  XSUNABA_XEPHYR_PID=$!
  sleep 1
  doas -u $XSUNABA_USER env DISPLAY=$XSUNABA_DISPLAY $APPLICATION

  # stop Xephyr
  if ps -p $XSUNABA_XEPHYR_PID >/dev/null; then
    kill $XSUNABA_XEPHYR_PID
  fi

  # clear authentication cookie after session is closed
  xauth -f $XSUNABA_XAUTH remove $XSUNABA_DISPLAY
  doas -u $XSUNABA_USER xauth remove $XSUNABA_DISPLAY
else
  # display is active so application is already running
  # show simple error message
  if [ -n "$(which xmessage)" ]; then
    xmessage -buttons OK -center "Application is already running. Display ${XSUNABA_DISPLAY#:} is active."
  fi
fi
